# Generated by gallery/generate.py; do not edit.
function naturesaura_gallery:clear
fill 172 99 172 204 99 192 minecraft:smooth_stone
# stock-control: stone stock control
setblock 174 100 174 minecraft:stone
# altar-empty: empty Nature Altar
setblock 176 100 174 naturesaura:nature_altar
# altar-item: Nature Altar with block item
setblock 178 100 174 naturesaura:nature_altar
data merge block 178 100 174 {items:{Size:1,Items:[{Slot:0b,id:"minecraft:gold_block",count:1}]}}
# offering-empty: empty Offering Table
setblock 180 100 174 naturesaura:offering_table
# offering-items: Offering Table with eight items
setblock 182 100 174 naturesaura:offering_table
data merge block 182 100 174 {items:{Size:1,Items:[{Slot:0b,id:"minecraft:gold_block",count:8}]}}
# stand-block: Wood Stand block-item branch
setblock 184 100 174 naturesaura:wood_stand
data merge block 184 100 174 {items:{Size:1,Items:[{Slot:0b,id:"minecraft:gold_block",count:1}]}}
# stand-sprite: Wood Stand flat-item branch
setblock 186 100 174 naturesaura:wood_stand
data merge block 186 100 174 {items:{Size:1,Items:[{Slot:0b,id:"minecraft:stick",count:1}]}}
# ender-crate: Ender Crate portal surface
setblock 188 100 174 naturesaura:ender_crate
# timer-end-half: half-filled End Aura Timer
setblock 190 100 174 naturesaura:aura_timer
data merge block 190 100 174 {items:{Size:1,Items:[{Slot:0b,id:"naturesaura:aura_bottle",count:1,components:{"naturesaura:aura_bottle_data":{aura_type:"naturesaura:end"}}}]},timer:36000}
# projectile-north: Projectile overlay north
setblock 174 100 180 naturesaura:projectile_generator
data merge block 174 100 180 {next_side:2}
# projectile-east: Projectile overlay east
setblock 176 100 180 naturesaura:projectile_generator
data merge block 176 100 180 {next_side:5}
# projectile-south: Projectile overlay south
setblock 178 100 180 naturesaura:projectile_generator
data merge block 178 100 180 {next_side:3}
# projectile-west: Projectile overlay west
setblock 180 100 180 naturesaura:projectile_generator
data merge block 180 100 180 {next_side:4}
# generator-limiter: active generator limiter
setblock 183 100 180 naturesaura:generator_limit_remover
# generator-target: limiter projectile target
setblock 183 101 180 naturesaura:projectile_generator
data merge block 183 101 180 {next_side:2}
# lower-target-nonfull: non-full lower-limiter target
setblock 186 100 180 naturesaura:spawn_lamp
# lower-limiter: lower limiter between targets
setblock 187 100 180 naturesaura:lower_limiter
# lower-target-full: full-cube lower-limiter target
setblock 188 100 180 naturesaura:ender_crate
# ancient-leaves: fixed pink ancient leaves
setblock 174 100 186 naturesaura:ancient_leaves
# golden-stage-0: golden leaves biome stage
setblock 176 100 186 naturesaura:golden_leaves[stage=0]
# golden-stage-1: golden leaves blend one
setblock 177 100 186 naturesaura:golden_leaves[stage=1]
# golden-stage-2: golden leaves blend two
setblock 178 100 186 naturesaura:golden_leaves[stage=2]
# golden-stage-3: golden leaves final color
setblock 179 100 186 naturesaura:golden_leaves[stage=3]
# gold-powder-west: connected gold powder west
setblock 182 100 186 naturesaura:gold_powder
# gold-powder-center: connected gold powder center
setblock 183 100 186 naturesaura:gold_powder
# gold-powder-east: connected gold powder east
setblock 184 100 186 naturesaura:gold_powder
# spring-water: Spring water-tinted layer
setblock 187 100 186 naturesaura:spring
function naturesaura_gallery:verify
